# Uncomment the next line to define a global platform for your project
	platform :ios, '9.0'

target 'NGW-mobile' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for NGW-mobile

	pod 'OneSignal', '~> 2.5.2'

	pod 'FBSDKCoreKit'
	pod 'FBSDKLoginKit'
	pod 'FBSDKShareKit'
	pod 'AccountKit'

	pod 'FBSDKPlacesKit'
	pod 'Firebase'
	pod 'Firebase/Core'
	pod 'Firebase/Database'
	pod 'Firebase/Auth'

end
